UI Create Build Type Tests
ma1m2/teamcity pull request #2
Opened 2024-11-10 18:10 UTC by ma1m2

2024-11-21 12:05 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-21 12:05 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +                .getErrorEmptyRepoUrl().errorUrl.shouldHave(Condition.exactText("URL must not be empty"));
Отлично! Не хватает проверки на уровне API, что сущность не создалась.

2024-11-25 08:27 UTC, ma1m2 commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +                .getErrorEmptyRepoUrl().errorUrl.shouldHave(Condition.exactText("URL must not be empty"));
Я добавила проверку на уровне API, что сущность не создалась.

2024-11-26 22:02 UTC, nobugs-me approved these changes
Спасибо, теперь все корректно 🙌

2024-11-26 23:31 UTC, nobugs-me approved these changes

2024-11-28 21:32 UTC, merged